steps:
#builds the image
- name: 'docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops','.']
#push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
#deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gkedeploy.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-west1-a
  - --cluster=gcp-devops-lifecycle #clustername
  - --namespace=gcp-lifecycle-prod