apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-lifecycle-gke
spec:
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-lifecycle-gke
        #enter your gcp user-name in place of user-name
        image: gcr.io/<user-name>/gcpdevops:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
    replicas: 1
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gcp-lifecycle-gke-service"
  namespace: "gcp-lifecycle-prod"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build"
spec:
  selector:
    app: gcp
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: "LoadBalancer"
